### ISSUE TITLE
compiler issues due to import names changing

### ISSUE THREAD

**Issue by borovan** [aviate-labs/rand.mo#1]
.vessel/ulid/v0.1.3/src/Source.mo:1.1-1.35: import error [M0010], package "base-0.7.3" not defined
.vessel/ulid/v0.1.3/src/Source.mo:4.1-4.37: import error [M0010], package "base-0.7.3" not defined

hey do you know how to import the new files?  I'm not sure what to add to my package-set.dhall file to make these new versions work.

Thanks

**Comment by q-uint** [comment]
Hi @borovan! I would recommend installing it through the [package-set](https://github.com/aviate-labs/package-set) or compare your `package-set.dhall` with the [one in the repository](https://github.com/aviate-labs/rand.mo/blob/main/package-set.dhall).
